server.port=8080

# Spring Application Name
spring.application.name=nool-credit-backend

# MongoDB Configuration
spring.data.mongodb.uri=mongodb+srv://keerthivasanr39_db_user:NoolCredit123@cluster0.vugdefc.mongodb.net/nool_credit_db?retryWrites=true&w=majority&appName=Cluster0
spring.data.mongodb.auto-index-creation=true

# JWT Configuration
nool.jwt.secret=noolCreditSuperSecretSecretKeyForHackathon2026ModernFinTechPlatformDemoSecurityKey
nool.jwt.expiration-ms=86400000
